@extends('layouts.test')
@section('content')
<h1 class="text-2xl font-bold">Admin Dashboard</h1>
<div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">@foreach(['Clients'=>$clientsCount,'Appointments'=>$appointmentsCount,'Orders'=>$ordersCount,'Today revenue'=>$todayRevenue,'Month revenue'=>$monthlyRevenue] as $label=>$value)<div class="rounded bg-white p-4 shadow"><p class="text-sm text-slate-500">{{ $label }}</p><p class="text-2xl font-bold">{{ $value }}</p></div>@endforeach</div>
<div class="flex flex-wrap gap-3"><a class="text-blue-600" href="{{ route('admin.users.index') }}">Users</a><a class="text-blue-600" href="{{ route('admin.appointments.index') }}">Appointments</a><a class="text-blue-600" href="{{ route('admin.orders.index') }}">Orders</a></div>
<div class="grid gap-4 lg:grid-cols-3">
<form method="POST" action="{{ route('admin.categories.store') }}" class="grid gap-2 rounded bg-white p-4 shadow">@csrf<h2 class="font-bold">Add Category</h2><input class="border p-2" name="name" placeholder="Name"><textarea class="border p-2" name="description" placeholder="Description"></textarea><button class="bg-blue-600 p-2 text-white">Save</button></form>
<form method="POST" action="{{ route('admin.services.store') }}" enctype="multipart/form-data" class="grid gap-2 rounded bg-white p-4 shadow">@csrf<h2 class="font-bold">Add Service</h2><input class="border p-2" name="name" placeholder="Name"><input class="border p-2" name="price" placeholder="Price"><input class="border p-2" name="duration" placeholder="Duration"><textarea class="border p-2" name="description" placeholder="Description"></textarea><input type="file" name="image"><button class="bg-blue-600 p-2 text-white">Save</button></form>
<form method="POST" action="{{ route('admin.products.store') }}" enctype="multipart/form-data" class="grid gap-2 rounded bg-white p-4 shadow">@csrf<h2 class="font-bold">Add Product</h2><select class="border p-2" name="category_id">@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><input class="border p-2" name="name" placeholder="Name"><input class="border p-2" name="price" placeholder="Price"><input class="border p-2" name="stock_quantity" placeholder="Stock"><textarea class="border p-2" name="description"></textarea><input type="file" name="image"><button class="bg-blue-600 p-2 text-white">Save</button></form>
</div>
<h2 class="text-xl font-bold">Manage categories</h2>@foreach($categories as $category)<div class="rounded bg-white p-3"><form method="POST" action="{{ route('admin.categories.update',$category) }}" class="flex flex-wrap gap-2">@csrf @method('PUT')<input class="grow border p-1" name="name" value="{{ $category->name }}"><input class="grow border p-1" name="description" value="{{ $category->description }}"><button>Update</button></form><form method="POST" action="{{ route('admin.categories.destroy',$category) }}">@csrf @method('DELETE')<button class="text-red-600">Delete</button></form></div>@endforeach
<h2 class="text-xl font-bold">Manage services</h2>@foreach($services as $service)<div class="rounded bg-white p-3"><form method="POST" action="{{ route('admin.services.update',$service) }}" class="flex flex-wrap gap-2">@csrf @method('PUT')<input class="border p-1" name="name" value="{{ $service->name }}"><input class="w-24 border p-1" name="price" value="{{ $service->price }}"><input class="w-24 border p-1" name="duration" value="{{ $service->duration }}"><input type="hidden" name="description" value="{{ $service->description }}"><button>Update</button></form><div class="flex gap-3"><a href="{{ route('admin.services.appointments',$service) }}">Bookings</a><form method="POST" action="{{ route('admin.services.toggle-status',$service) }}">@csrf<button>Toggle {{ $service->is_active?'off':'on' }}</button></form></div></div>@endforeach
<h2 class="text-xl font-bold">Manage products</h2>@foreach($products as $product)<div class="rounded bg-white p-3"><form method="POST" action="{{ route('admin.products.update',$product) }}" class="flex flex-wrap gap-2">@csrf @method('PUT')<select name="category_id">@foreach($categories as $category)<option value="{{ $category->id }}" @selected($category->is($product->category))>{{ $category->name }}</option>@endforeach</select><input class="border p-1" name="name" value="{{ $product->name }}"><input class="w-24 border p-1" name="price" value="{{ $product->price }}"><input class="w-24 border p-1" name="stock_quantity" value="{{ $product->stock_quantity }}"><input type="hidden" name="description" value="{{ $product->description }}"><button>Update</button></form><form method="POST" action="{{ route('admin.products.toggle-status',$product) }}">@csrf<button>Toggle {{ $product->is_active?'off':'on' }}</button></form></div>@endforeach
@endsection
